examples/req_with_payload.js
Added example passing a payload object through the request
=> Created req_with_payload.js

test/proxy.js
Tests to cover the Observe features for proxied servers. Doesn't involve any changes in the code.
=> Add tests for observe features in proxyed servers

lib/server.js, test/ipv6.js, test/server.js
=> Fix missing handler

lib/helpers.js, lib/middlewares.js, test/proxy.js
=> Fix Observes through proxy

README.md
I would like to help maintaining this project
=> New contributor

README.md, index.js, lib/helpers.js, lib/option_converter.js, test/end-to-end.js
See #78.  I find this pretty damn useful, and we can add things to the list as necessary.
Added docs/test
=> add `ignoreOption()` function; closes #78

README.md, examples/multicast_client_server.js, lib/agent.js, lib/server.js, test/request.js, test/server.js
Here multicast request and server support is added.
Related issue https://github.com/mcollina/node-coap/issues/6
=> Multicast server and request support

examples/delayed_response.js
=> add delayed reponse examle

lib/agent.js, lib/helpers.js, lib/middlewares.js, lib/observe_write_stream.js, lib/outgoing_message.js, lib/parameters.js, lib/server.js, test/server.js
=> add piggyback timing to parameters.js

lib/option_converter.js, test/end-to-end.js, test/request.js, test/server.js
Adding the necessary enumeration for CBOR support
=> Updates to add CBOR support

README.md, lib/helpers.js, lib/parameters.js, lib/server.js, test/server.js
RFC, this is an update for Issue #108 
missing a function test, but i would like to get some feedback first
=> opt out ack packages for non confirmable messages

lib/agent.js, test/agent.js
=> Do not send ACK for unrecognized CON message

lib/server.js, test/blockwise.js
=> Fix blockwise2 transfer for multiclient use-case; change single-entry block2Cache to multi-entry cache

README.md, lib/option_converter.js, test/end-to-end.js
This option is pretty useful and defined in the CoAP RFC, I think node-coap should support it.
I don’t know what is the best way to test it?
=> Add Max-Age support

lib/server.js
Suggestions for unit testing are welcome.
=> Bind to multiple interfaces for multicast

README.md, index.js, lib/agent.js, lib/server.js, test/request.js, test/share-socket.js
To support one socket as both server and client.
=> Allow using existing socket

.travis.yml, index.js, lib/agent.js, lib/helpers.js, lib/incoming_message.js, lib/middlewares.js, lib/observe_read_stream.js, lib/observe_write_stream.js, lib/option_converter.js, lib/outgoing_message.js, lib/parameters.js, lib/polyfill.js, lib/retry_send.js, lib/server.js
found the ìnterface` issue when doing some webpack magic
=> enable strict mode, rename reserved word

lib/agent.js, test/agent.js
Fix the wrapper bug of `new Agent` and remove useless variable in `agent.test.js`
=> fix(agent): fix agent config bug

lib/agent.js
These variables have never been used.
=> fix(agent): remove useless variables

lib/agent.js
=> Fix: Retrysend broken when passing socket to agent

CHANGELOG.md, package.json
BEFORE we merge this we need to finally decide about https://github.com/mcollina/node-coap/pull/211 and pot. add it ... or ot :-)
=> bumb version and add Changelog file

examples/blockwise_put.js, examples/json.js
This PR fixes bugs that caused two examples to not properly work. After merging this PR they will work again.
=> fix: fix bugs in two examples

test/request.js
This PR might be a fix for the random test failures that occur from time to time.
=> fix: increase timeout for invalid packets test

README.md, lib/server.js
This PR would fix #268. I am not sure, however, if this change is really necessary/desirable. I am looking forward to any comments on this :) 
CC @fillobotto @relu91
=> fix(server): allow only one server instance for each port number

.gitignore, index.d.ts, lib/agent.d.ts, lib/incoming_message.d.ts, lib/outgoing_message.d.ts, lib/server.d.ts, package.json, ts/test.ts, tsconfig.json
This PR adds a couple of declaration files to the project to enable typescript support. This might also be a first step for potentially porting the project to typescript in the future.
I added a first test to ensure that the type declarations work. There probably is some room for improvement, though. @relu91: Maybe you could also have a look on this PR? :)
=> feat: add typescript declarations

test/helpers.js
This PR adds a test for the `toCode` helper function, increasing test coverage.
=> test(helpers): add test for toCode

lib/block.js, lib/cache.js, lib/helpers.js, lib/option_converter.js, lib/segmentation.js, test/end-to-end.js, test/ipv6.js, test/request.js, test/share-socket.js
Trivial PR that reduces the diff size of #293.
=> style: refactor string concatenation

lib/agent.js, lib/cache.js, test/cache.js
This PR introduces some small refactoring in preparation for #293.
=> refactor: use Maps instead of Objects for caching

test/agent.js, test/blockwise.js, test/common.js, test/end-to-end.js, test/helpers.js, test/ipv6.js, test/parameters.js, test/proxy.js, test/request.js, test/retry_send.js, test/segmentation.js, test/server.js, test/share-socket.js
This PR makes some more minor adjustments to avoid errors when checking for type and null safety.
=> test: refactor and fix tests

lib/middlewares.js, lib/server.js
This PR includes some more minor changes to decrease the diff size of #293.
=> refactor: refactor middlewares

lib/server.js
=> fix(server): replace null check for reuseAddr option

CHANGELOG.md, package.json
This PR makes some preparations for the release of version 0.26.0 and updates the changelog.
=> chore: prepare the release of version 0.26.0

package.json
This PR updates the version number to prepare the release of version 1.0.1.
=> chore: prepare the release of version 1.0.1

lib/option_converter.ts, test/end-to-end.ts
I noticed that the two options are currently not supported. This PR adds them as additional features to the project.
=> feat: add support for Size2 and Size 1 options

lib/server.ts
=> fix: keep user-defined options during block2 transfers

package.json
This PR bumps the version in the `package.json` file to finally prepare for a new release. :)
Will resolve #381.
=> Prepare release 1.4.0
