coapjs/node-coap

- README.md
- lib/agent.js
- lib/incoming_message.js
- lib/observe_read_stream.js
- test/request.js
Add a property in the response listener for the requests to allow the caller to retrieve information about the socket used in the communication (port, address and protocol). This addition was motivated by the need of identifying the device original address in COAP-based OMA Lightweight M2M protocol as explained in issue #39 (originally the need was to use the same socket for listening and sending requests, but having information about the registration socket might lead to avoid the sharing, as explained in a comment).
I choose to expose the information as part of the `rsinfo` object (that was already passed to the IncomingMessage instance creation) and expose the latter in a `_rsinfo` internal attribute of the response, but I'm not 100% confident this is the best option. It covers the …
> Original address

- README.md
- lib/observe_write_stream.js
- lib/outgoing_message.js
- test/server.js
Add a Reset method to the Outgoing message, so a COAP RST message can be returned to the caller.
> Add reset method

- lib/server.js
- test/server.js
With the current behavior, an incoming request with an unknown 'Content-Format' option generates an unexpected exception that makes the server crash. I've captured the exceptions in the message handling, to return an error to the user, indicating that the request could not be handled.
> Server shut down on unexpected option

- README.md
- examples/proxy.js
- lib/agent.js
- lib/middlewares.js
- lib/option_converter.js
- lib/server.js
- package.json
- test/proxy.js
Adds two features to the library:
* Add the `proxy` option to the server creation, so the server will behave like a COAP Proxy: if a request arrives containing the Proxy-Uri Option, instead of treating it like a normal request, it is forwarded to the destination indicated in the Option, removing the Proxy-Uri option from the package.
* Add the `proxyUri` option to the request options, so it can be directly indicated in the request creation (just adds the Proxy-Uri option to the final request).
In order to implement the server option, an important refactor in the request handler was done. I extracted the request handler function to a top-level function, and decomposed the process into a `parseRequest` and a `handleServerRequest` function. This functions were composed as a concatentation of …
> Single socket

- lib/middlewares.js
- test/proxy.js
With the last changes (the introduction of "fastseries"), the standard server functionality for servers with the proxy feature activated was broken, i.e: if a server is created with the `proxy` option, and a request is sent without the `proxyUri` option, the usual handler should be called, but, with the last modifications, a `missing request` error is received instead. This PR address that case.
> Fix server functionality in proxies

- lib/agent.js
- lib/retry_send.js
- test/request.js
I have added a 'timeout' event at RetrySend, and it is captured by the Agent that cleans up the request and avoids keeping a reference to a request that never will be completed
> Fix request error leak

- lib/agent.js
- lib/polyfill.js
- lib/server.js
- test/request.js
Added a guard to check that the token in the response is the same that the one in the request, except for 0.00 messages. Right now the behavior is to ignore messages with different tokens, so if no correct message arrives, a timeout will be emitted.
> Check token integrity in reponses

- lib/agent.js
- test/request.js
Fix crash when receiving duplicate CON responses. Right now the behavior when receiving a duplicate CON response is to ignore it and return.
> Fix crash when receiving duplicate CON responses

- README.md
- lib/helpers.js
- lib/option_converter.js
- lib/outgoing_message.js
- package.json
- test/end-to-end.js
- test/request.js
- Add `capitalize` package as dependency
- To normalize option names, capitalize each word of the name.  "content-format" becomes "Content-Format", etc.  special case for "ETag", which was added to the alias map.
- Fixed an undefined variable in `option_converter`'s `contentFormatToBinary()`
- Added `OutgoingMessage.prototype.writeHead()` as to provide more compatibility with the `http` module
- Encoding information can be sent in *any* `Content-Format` value, but it is discarded.  From what I can gather from the RFC7252 and other RFCs I read, we only seem to be *required* to accept the encoding information with `text/plain`; support any other format would be optional, but since sending a type such as `application/json; charset=utf-8` is so common, we may as well
- Updated `README.md` …
> normalize names, encoding information & writeHead; closes #71 and #73

- lib/server.js
- test/server.js
Simple if-guard. Throwing an error probably not desirable, since when calling `close` we want it closed; if it already is closed then there's no error in the outcome, just an odd request.
> guard against closing closed/never-opened socket

- lib/retry_send.js
Hi,
I've fixed a critical bug when packets are lost in the middle of a blockwise transfer. There was a unique counter for send attemps for ALL messageIds. Since this counter was incremented every new message, once you send more that 5 messages, the attempt counter is over the limit and no retries will be performed.
I've added a field in RetrySend to keep track of the messageId, and reset counter and currentTime when messageID changes.
I've not added any test since this is just a bugfix and it does not introduce new functionality. Besides, I don't know how to mock a blockwise transfer ...
> CRITICAL: fix request hangs when using blockwise transfers in unreliable networks

- lib/server.js
I was trying to run the 'multicast_client_server' example, but was throwing 'EADDRINUSE' bind error.
I ended founding the explanation on this thread: https://github.com/mdns-js/node-mdns-js/issues/31
Just one change on 'lib/server.js' and the example worked. So i made this little pull request.
Hope that helps. 
P.s.: running more than one server in different process also work
Note: i tested on node v0.12.7
> Allow more than one multicast server to bind on same port and address

- README.md
- index.js
- lib/parameters.js
- test/parameters.js
This pull requests adds the option to customize the coap timings, you can for example customize the maximal RTT for a coap package, redefine retires etc.
Note: I removed some unreferenced parameters:
- nstart
- defaultLeisure
- probingRate
> Customize CoAP parameters

- README.md
It seems this is supported now (for the last 9 versions).
> Remove notice about blockwise not being supported

- test/proxy.js
The error code apparently depends on some configuration. Adding this
one in order to have tests passing in my development environment.
> Accept EAI_AGAIN as DNS failure

- .travis.yml
- lib/parameters.js
- lib/server.js
- test/request.js
- test/server.js
> Fix LRU cache bloat

- lib/agent.js
- lib/retry_send.js
- test/request.js
I could not find an exact statement whether non-confirmable request CAN/SHOULD/MUST [NOT] be retried. But IMO it SHOULD be sent only once, especially for multicast requests. Also, tools like Californium send only one non-confirmable request, even if retry option is selected.
> Do not retry non-confirmable requests

- README.md
- lib/agent.js
- lib/retry_send.js
- test/retry_send.js
Currently node-coap does not allows to set separate options for client and server. My use case: coap server should retransmit 3 times, but the other way around I want only one retransmit.
Thats why this PR, it allows to set a custom retry count for a new CoAP request.
Tests are missing, I just want to get some feedback first
> add new option for retrySend

- lib/agent.js
- lib/outgoing_message.js
- test/request.js
- test/server.js
This PR fixes several issues when processing RST packets, including original issue #154:
* Server sends RST packet with token
* Server sends NON '5.00' "Empty message must be empty" after the RST
* Server sends ACK after the RST
* In rare occasions client may send a RST message in response to RST
* Request does not finish after receiving RST (cleanUp is not called, so the program just "hangs" without finishing)
Could anyone review the changes? @mcollina @neophob?
Also, I was unsure how should I handle a RST as a response - at first I did a separate req.on('reset') event, but then just slapped RST into response as it does not alter the API. Which do you guys think is better?
> Add RST packet processing fixes

- lib/agent.js
- test/share-socket.js
I use an Agent with existing socket. It will call `agent._cleanUp()` to set `agent._closing` to be `true` as soon as it receive a response. Then `agent._doClose()` will be called and `req.sender._timer` will be cleared when I use the same Agent to send requests. Therefore, timeout error event will never be fired. I recognize that `agent._closing` should not be set to `true` when Agent using existing socket.
> Fix without timeout error when using existing socket

- lib/agent.js
- test/request.js
See issue #205.
The idea here is to remove the token-to-request mapped value after the multicast timer times out. Currently, the token is removed once the first response is handled, which prevents other responses from being handled.
Added a test with two servers handling a request. Each server responds with a different MID, thus the response is not mapped using the mid-to-requst map.
> Fixes multiple responses to a non-confirmable multicast request

- README.md
- examples/blockwise.js
- examples/delayed_response.js
- lib/agent.js
- lib/helpers.js
- lib/observe_write_stream.js
- lib/option_converter.js
- lib/server.js
- test/agent.js
- test/blockwise.js
- test/ipv6.js
- test/proxy.js
- test/request.js
- test/server.js
This fixes warnings because of deprecated `Buffer` api, see here: https://nodejs.org/fr/docs/guides/buffer-constructor-deprecation/
> Upgrade Buffer api

- lib/helpers.js
- lib/server.js
- test/blockwise.js
If the payload was an exact multiple of the block size the index calculation was off by one.
This caused clients to make an additional redundant request at the end.
Also, GET requests would always have the more flag set, which was against the specs.
> Fix more flag during block-wise transfer

- .github/workflows/npm-test.yml
- .travis.yml
- README.md
- package.json
This PR will resolve #224. Tests are now performed on Node versions 10.x, 12.x, 14.x, 15.x, and on multiple platforms (Ubuntu, Windows, Mac OS). One test on Mac OS, however, fails at the moment. This problem should either be fixed or Mac OS should be skipped for testing for now.
The CI pipeline now also generates a coverage report and supports `coveralls` which can be used for including a badge in the readme. I also thought about including a linting step using JSHint or ESLint but I guess this would require some configuration due to the used coding style.
> chore: move CI to Github Actions

- lib/agent.js
- test/request.js
This PR offers a potential fix for #236. As mentioned in the issue (and suggested by [RFC 7959](https://tools.ietf.org/rfcmarkup/7959#section-2.8)), the agent now switches to unicast requests if a response containing a block2 option is given to a multicast request. 
This solves a problem that occured if two servers offering providing the same resource path are reachable over the same multicast address leading to confusion in the agent as the same block numbers are requested over and over again from the multicast address once a new reponse arrives.
This PR is still a bit WIP as the new `_convertMulticastToUnicastRequest` function could probably be refactored if there is a more elegant way to perform a deep copy of the initial request. I am also still working on corresponding unit tests. …
> Fix handling of block2 reponses to multicast requests

- lib/agent.js
- test/request.js
This PR fixes a small bug that was included in #237 by "copying" not only the listeners for `response` events but for all events registered to a multicast request when converting it to a unicast request. Copying only `reponse` listeners could lead, for example, to unhandled `error` events causing an application to crash.
> fix: copy all listeners when using block2 multicast

- lib/agent.js
- test/request.js
I noticed three more (and hopefully last) problems with block-wise transfer and multicast requests which are addressed by this PR. 
First, I noticed that when performing a multicast request nodes could reply multiple times leading to more messages than required and, more importantly, duplicated payloads which could lead to unintended behavior. I fixed this problem by keeping track of the hostnames of the respondants that replied to the inital multicast request. If a server replies twice to a multicast, all reponses after the first one will be ignored. 
A second fix addresses the fact that the multicast timer from the initial request got reinitialized in the converted unicast request causing the client to abort the transfer once the time limit was reached. Using `clearTimeout()`, this …
> Fix three more problems with blockwise multicast responses

- lib/agent.js
- lib/observe_read_stream.js
- lib/server.js
- test/proxy.js
- test/request.js
- test/server.js
This is a superset of pull request #164, bringing forward and building on the work of @pekkanikander.  Since this alone didn't go all the way to solving issue #195, I also bit the bullet and implemented that too.
Due to the commit hooks set up on this repository, I was forced to fix a few other issues as part of this pull request, notably the "leaking" of exceptions by some callback functions, as well as extending the time-outs on some unhappy path tests that were failing simply because some network operations were taking a bit longer to signal an error.
Finally, since it's required for RFC-7641, I have added the ability for a user to specify their own token, that way when de-registering, we can honour the spec and send the correct token to the CoAP server.
Since the de-registration would …
> Add support for de-registering observations

- README.md
This PR updates the README in accordance to the newly added feature for type 1 block-wise transfer. I created a PR for this change as I wanted to be sure that this actually going to be a new *minor* release.
> Add version info on type 1 block-wise transfers to README

- README.md
Let the README reflect that `ObserveWriteStream` does not actually implement the  `OutgoingMessage` interface.
Merging this PR will make PR #177 obsolete (for now at least).
> docs: fix ObserveWriteStream interfaces in README

- lib/option_converter.js
This PR adds more content-formats the library that are available by default. There are still codes that could be added, see [this IANA page](https://www.iana.org/assignments/core-parameters/core-parameters.xhtml#content-formats) for the full list of available CoAP content-formats.
I am not sure about the current way the formats are registered. Maybe it makes more sense to define them as an array somewhere and then iterate over them at startup?
> feat: add more content-formats

- README.md
This PR updates the README file with the RFC numbers for the implemented specifications and removes the reference to their drafts.
> chore: change drafts to RFCs in README

- README.md
- lib/server.js
- test/server.js
This PR is a follow-up to #190. It fixes a couple of issues that were present on that branch, cleans up the commit history, and removes the added `package.json` file.
> feat: add `clientIdentifier` option to `createServer`

- README.md
This PR is only a minor adjustment for the examples in the readme which still used the pre-ES2015 syntax. I thought it would be nice to update the readme in this regard to reflect that the package is still up to date ;)
Regarding the actual content of the readme, I also noticed that the list of content formats that are supported by default could be updated to reflect the updates made in #248. I would open a separate PR for this, however.
> style: Update JS style in readme examples

- lib/agent.js
This PR removes code that checks for node version 4 which is EOL for a couple of years.
> refactor(agent): remove obsolete DNS bug check

- index.js
- lib/agent.js
- lib/cache.js
- lib/incoming_message.js
- lib/observe_read_stream.js
- lib/observe_write_stream.js
- lib/outgoing_message.js
- lib/retry_send.js
- lib/segmentation.js
- lib/server.js
- test/agent.js
- test/retry_send.js
- test/segmentation.js
This PR refactors the pre ECMAScript 2015 prototype approach used in a number of files and introduces classes instead. This should make the code a lot easier to read and also improve the project's maintainability
> refactor: replace prototypes with classes 

- lib/agent.js
- lib/observe_write_stream.js
- lib/outgoing_message.js
- lib/retry_send.js
- lib/server.js
This PR removes the
```js
const that = this
```
statements from the codebase and replaces occurences of `that` with `this` by using arrow functions which allow for calling `this` directly. This should make the code easier to read.
> refactor: replace `that` with `this` by using arrow functions

- README.md
- examples/blockwise.js
- examples/blockwise_put.js
- examples/client.js
- examples/client_and_server.js
- examples/delayed_response.js
- examples/json.js
- examples/multicast_client_server.js
- examples/observe_client.js
- examples/observe_server.js
- examples/proxy.js
- examples/req_with_payload.js
- examples/server.js
- index.js
- lib/agent.js
- lib/block.js
- lib/helpers.js
- lib/option_converter.js
- lib/parameters.js
- lib/polyfill.js
- lib/server.js
- test/agent.js
- test/blockwise.js
- test/common.js
- test/end-to-end.js
- test/ipv6.js
- test/proxy.js
- test/request.js
- test/server.js
- test/share-socket.js
This PR should make the codebase a bit more concise by getting rid of most of the `function` statements which are no longer necessary due to the addition of error functions.
An exception to this are the `function` statements used in the `mocha` tests as passing arrow functions to `mocha` is [discouraged](https://mochajs.org/#arrow-functions).
> refactor: replace unneeded `function` statements with arrow functions

- lib/agent.js
- test/agent.js
This is a small fix which allows message IDs to be set to 0 if the maximum message ID value has been reached. This makes the implementation a bit more consistent as the initial message ID can actually be 0.
As a bug in `coap-packet` has been fixed that caused errors when the ID was 0 this change should be fine to add now.
> fix(agent): reset _lastMessageId to 0

- README.md
- examples/blockwise.js
- index.js
- lib/server.js
This PR replaces `URL.parse` which is deprecated according to eslint. It fixes #267.
> refactor: replace deprecated URL.parse

- index.d.ts
- lib/agent.d.ts
- lib/incoming_message.d.ts
- lib/incoming_message.js
- lib/observe_read_stream.d.ts
- lib/observe_read_stream.js
- lib/server.d.ts
- ts/test.ts
This PR adds a couple of improvements to the type declarations (especially with regard to `ObserveReadStream`), including copyright headers. The implementation of `ObserveReadStream` also refactored by letting it inherit from `IncomingMessage`.
> feat: refactor and add type declarations for `ObserveReadStream`, add copyright headers

- README.md
This PR fixes a deprecated `Buffer` instantiation example in the README file.
> docs: fix `Buffer` code for Block1 option in README

- .npmignore
I noticed that there a couple of configuration files as well as the coverage output included in published packages. This PR adjusts the `.npmignore` file accordingly as it overwrites `.gitignore` files when it exists.
> chore: ignore auxiliary files when publishing npm package

- lib/agent.js
This PR does some small refactoring and removes a couple of unneeded statements from the agent.
> refactor(agent): remove obsolete token statements

- examples/blockwise.js
I noticed that there is currently a problem in one of the examples that is caused by the replacement of `url.parse` with the native URL constructor. This PR provides a quick and dirty fix that should be revisited in the future.
> fix(examples): fix problem caused by `new URL`

- README.md
- lib/helpers.js
- lib/server.js
- test/server.js
This PR adds support for the FETCH, PATCH, and iPATCH CoAP methods, as specified in [RFC 8132](https://datatracker.ietf.org/doc/html/rfc8132). I still need to figure out what is actually needed to fully support these methods (besides the status codes), so this PR is for now only opened as a draft.
> feat: add support for FETCH, PATCH, and iPATCH

- lib/agent.js
- lib/block.js
- lib/helpers.js
- lib/segmentation.js
- lib/server.js
- test/blockwise.js
- test/helpers.js
- test/segmentation.js
So far both the data structures as well as the terminology in block1 and block2 block state options differed. In preparation for more consistent typing this PR applies some more cleanup to the project.
> refactor: unify block1 and block2 terminology

- lib/agent.js
- lib/observe_read_stream.js
- lib/observe_write_stream.js
- lib/option_converter.js
- lib/outgoing_message.js
- lib/retry_send.js
- lib/segmentation.js
- lib/server.js
- test/agent.js
- test/blockwise.js
- test/cache.js
- test/end-to-end.js
- test/helpers.js
- test/ipv6.js
- test/parameters.js
- test/proxy.js
- test/request.js
- test/segmentation.js
- test/server.js
- test/share-socket.js
This PR adds most of the `null` and type checks from #293 to the current state of the project to further decrease diff size. The project should also already benefit a little from the changes in terms of stability and readability. For most part, the changes are rather trivial, though.
> refactor: apply last refactorings before 0.26.0

- .npmignore
This PR is a potential fix for the problem that tests files end up on npm. The change to the `.npmignore` file should prevent that in the future.
> chore: ignore test files in npm package

- lib/agent.ts
- test/agent.ts
- test/server.ts
This PR adds a `close` method to the `Agent` class that aborts all pending requests and resolves #312. To do so, a small bug is fixed in the `abort` method where the `_msgInFlight` hasn't been decremented when a request is cancelled.
An additional test is added to assert that the new method works as expected.
> feat(agent): add `close` method

- index.ts
This PR makes some small adjustments to `index.ts` where a couple of definitions weren't exported correctly. I think we could publish a (patch) version `1.0.1` after the merge of this PR.
> fix(index.ts): fix issues with exported types

- lib/outgoing_message.ts
This PR lets the `OutgoingMessage` transitively implement the `Duplex` interface from the `readable-stream` module by adding an implementation of the `BufferList` interface. This fixes compatibility issues with Node.js stream functions (and incorporates a recent [update](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57052) of the respective types module).
This PR is related to [this issue](https://github.com/eclipse/thingweb.node-wot/issues/642) in the [node-wot](https://github.com/eclipse/thingweb.node-wot) repository.
The PR does not change any functionality, therefore the CI should stay green.
> feat: let `OutgoingMessage` implement `BufferList` interface

- lib/agent.ts
- test/agent.ts
- test/request.ts
Hello, this is my first PR to this repository let me know if I have to change the commit style or if I skipped some steps. Regarding the PR I'm coming from https://github.com/eclipse/thingweb.node-wot/issues/637 where we found that node hanged after using coap client.  I've dug into the code and I found out that the problem arises when you close an `agent` when there are no pending requests running. Basically if you take a look at the current implementation code:
```ts
close (done?: (err?: Error) => void): this {
for (const req of this._msgIdToReq.values()) {
this.abort(req) // <-- never called if this._msgIdToReq.size === 0
}
if (done != null) {
setImmediate(done)
}
return this
}
```
The abort function is never called which in the end has the effect of not properly closing the socket. …
> Improve close logic and fix corner cases

- package.json
This PR fixes a typescript related issue raised in https://github.com/eclipse/thingweb.node-wot/issues/728 where the types for the `bl` and `lru-cache` modules could not be found during transpilation.
> fix: move bl and lru-cache types to dependencies

- lib/agent.ts
- models/models.ts
- test/agent.ts
This PR (probably) fixes an issue raised in https://github.com/iobroker-community-adapters/ioBroker.philips-air/issues/15 (I think). It seems as if https://github.com/mcollina/node-coap/pull/309 broke handling of the observe option as the value provided by the user is converted into a numeric one while the internal check expects a boolean. I am not entirely sure, yet, if this is the actual fix for the problem but it is probably a step into the right direction.
> fix: fix problem with (boolean) observe parameters

- lib/agent.ts
- package.json
While #330 mostly fixed the problems with the observe request parameter, it also introduced a new bug that caused the Agent to always set the observe option to 0 in requests. This PR fixes the issue, making the Agent behave normally again.
> fix(agent): fix bug in observe option check

- package.json
Having a look at [coveralls.io](https://coveralls.io/github/mcollina/node-coap), I noticed that code coverage seems to be a bit broken right now. I recently found a better tool than nyc called c8 that seems to work with V8's native code coverage capabilities and be used as a drop-in replacement, fixing typescript related issues with nyc. It also gets rid of one additional dev-dependency.
> chore: replace nyc with c8 for code coverage

- lib/server.ts
- package.json
- test/server.ts
I noticed that there is a problem with IPv6 multicast addresses in the server right now. This PR adds a test case to illustrate the problem and a workaround to fix it, as iterating over all IPv6 interfaces does not work as it does in the IPv4 case.
The new test is skipped in the case of Mac OS as there seem to be problems related to IPv6 multicast (`addMembership EADDRNOTAVAIL`).
> fix: fix IPv6 related multicast problem

- .github/workflows/npm-test.yml
- .nycrc.json
- package.json
I noticed that c8 was configured incorrectly, reporting also coverage for test files. This PR fixes that and performs some cleanup.
> chore: fix c8 configuration

- examples/observe_eclipse.js
- lib/observe_read_stream.ts
- test/request.ts
With this PR I think I finally found the fix for https://github.com/iobroker-community-adapters/ioBroker.philips-air/issues/15: As it turned out, a type check that I had introduced to make sure that only numeric Observe values are passed to the initialization of `ObserveStream` objects caused them to not be initialized at all.
This PR fixes the issue and illustrates that observing now finally works again with an example using the Eclipse Californium test server.
> fix: fix problem with observe responses without observe option

- package.json
At the moment, we also publish the Typescript source files when uploading to npm which increases the bundle size. This PR would exclude them from publishing. However, also including the source files potentially makes debugging easier for users of the library.
Do you think we should remove the source files? Then we could simply merge this PR. Or should we keep them?
> chore: exclude TS source files from publishing

- README.md
As we only test for node 12 and above at the moment, it probably makes sense to only test for these versions. As soon as node 12 is EOL, we should bump the version to 14.
> docs: describe compatible node versions in README

- lib/agent.ts
- package.json
This PR incorporates the suggested change by @Thousif-khan and should fix #336.
> fix: fix observe when receiving block2 response

- lib/agent.ts
- models/models.ts
- test/request.ts
- test/server.ts
This PR should finally fix the issues reported in https://github.com/iobroker-community-adapters/ioBroker.philips-air/issues/15 by encoding a value of zero in observe options with a length of zero bytes (as it has been the case before).
> fix: encode 0 in observe option with zero byte length

- lib/agent.ts
This is a fix for https://github.com/avency/coap-cli/issues/136. The case where the `observe` parameter is set to `false` has not been handled correctly, yet, causing clients to hang after a request has been finished.
> fix(agent): correctly handle `false` observe values

- lib/cache.ts
- package.json
In the context of https://github.com/eclipse/thingweb.node-wot/pull/846, I noticed that the server is currently not cleaning up timeouts in the `BlockCache` class correctly. This PR implements a simple fix.
> fix: correctly clear timeout in `BlockCache` class

- package.json
- test/blockwise.ts
This PR is a subset of #356, including the most important fix for `@types/bl` and reactivating the inactive tests. I'll rebase #356 once this one is merged – I had some problems getting the updated dependencies to work on Node 14 for some reason :/
> Fix problem with `bl` types, reactivate tests

- lib/agent.ts
- lib/server.ts
This PR applies a few minor refactorings to `agent.ts` and `server.ts`, making the code slightly more readable.
> refactor: apply minor refactorings to agent and server

- .github/workflows/lint.yml
- .github/workflows/npm-test.yml
- lib/server.ts
- package.json
- test/server.ts
Spin-off from #373 that upgrades the `lru-cache`, because it is a bit tedious to debug otherwise.
Also updates the Node versions used by the CI, since the most recent `lru-cache` version seems to be incompatible with Node 14. Since Node 14 is EOL by way, applying this update might be overdue anyway.
> chore: update lru-cache dependency, update Node versions in CI

- lib/outgoing_message.ts
- package.json
https://github.com/coapjs/node-coap/pull/378
> New try to fix the pr for the Fixed build issuee can only be default-imported using the 'esModule

- lib/parameters.ts
- lib/server.ts
- models/models.ts
- test/blockwise.ts
This is a fix for #375 where the server will attempt to generate a packet greater than the maximum allowable, which was set to 1280 bytes. This would occur if the size of the payload was less than 1280 bytes, but the size of the resulting CoAP message was greater than 1280 bytes after the headers were added.
The bug was introduced 9 years ago in d727d430d7c744a516d4c68d156ed6bf8262f7b7 and has some incorrect logic for dealing with message sizes. It would be very easy to simply revert those changes and call it a fix, but I wanted to try and understand what the author was trying to implement and to fix the implementation, rather than simply removing functionality.
In addition I've updated the tests to be more robust and to catch errors like this in the future.
The intent of the above …
> Fix blockwise response logic

- lib/server.ts
Starting a listener on a network alias fails, so do not include them in allAddresses function.
> Do not include network aliases (identified by same MAC)

- lib/helpers.ts
This PR simplifies the `toCode` function that converts numeric, HTTP-like codes into string-based CoAP codes.
> refactor: simplify toCode function

- package.json
As explained in https://github.com/isaacs/node-lru-cache/issues/354 old versions of lru-cache (<= 11.0.0) caused problems with new typescript releases (5.6.x). This PR upgrades the dependency to 11.0.x.
> Bump lru-cache version to 11.x

- package.json
This PR bumps the package's version to 1.4.1 in preparation of a new release. As @Apollon77 already agreed to publish a new patch release with the current state of the `master` branch in https://github.com/coapjs/node-coap/pull/392#issuecomment-2603239422, I will merge this one immediately.
> chore: bump version to 1.4.1
